apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsr-frontend-deployment
spec:
  selector:
    matchLabels:
      app: bsrapp-frontend
  replicas: 1 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: bsrapp-frontend
    spec:
      containers:
      - name: bsrapp-frontend
        image: magingeorge/frontend:JENKINS_BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
