apiVersion: v1
kind: Service
metadata:
  name: fronend-service
spec:
  type: NodePort
  selector:
    app: bsrapp-fronend
  ports:
    - protocol: TCP
      name: fronend
      port: 3001
      targetPort: 3001
      nodePort: 30001